#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin

cd /etc/sysconfig/network-scripts
. network-functions

CONFIG=$1
source_config

if [ "foo$2" = "fooboot" -a "${ONBOOT}" = "no" ]
then
	exit
fi

ifconfig ${DEVICE} ${IPADDR} netmask ${NETMASK}
route add -net ${NETWORK} netmask ${NETMASK} ${DEVICE}

. /etc/sysconfig/network

if [ "${GATEWAY}" != "" ]; then
	if [ "${GATEWAYDEV}" = "" -o "${GATEWAYDEV}" = "${DEVICE}" ]; then
		# set up default gateway
		route add default gw ${GATEWAY}
	fi
fi

/etc/sysconfig/network-scripts/ifup-post $1
